Project:
  Name: ''
  CIR-ID: ''
  InstitutionName: Karolinska Institutet
  InstitutionAddress: Nobels vag 9, 171 77, Stockholm, Sweden
  InstitutionDepartmentName: Department of Clinical Neuroscience (CNS)
  Description: project for MEG data
  Tasks:
  - ''
  Root: /neuro/data/local/
  Raw: /neuro/data/local/<project>/raw
  BIDS: /neuro/data/local/<project>/BIDS
  Calibration: /neuro/data/local/<project>/databases/sss/sss_cal.dat
  Crosstalk: /neuro/data/local/<project>/databases/ctc/ct_sparse.fif
  Logfile: pipeline_log.log
BIDS:
  Dataset_description: dataset_description.json
  Participants: participants.tsv
  Participants_mapping_file: participant_mapping_example.csv
  Conversion_file: bids_conversion.tsv
  Overwrite_conversion: false
  Original_subjID_name: old_subject_id
  New_subjID_name: new_subject_id
  Original_session_name: old_session_id
  New_session_name: new_session_id
  overwrite: false
  dataset_type: raw
  data_license: ''
  authors: ''
  acknowledgements: ''
  how_to_acknowledge: ''
  funding: ''
  ethics_approvals: ''
  references_and_links: ''
  doi: doi:<insert_doi>
